file_format: "1"
id: thorne
name: thorne
type: shield
url: https://github.com/sirvati/zmk-config-thorne 
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - thorne_left
  - thorne_right