file_format: "1"
id: corne
name: corne
type: shield
url: https://github.com/sirvati/zmk-config-thorne 
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - corne_left
  - corne_right